version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: portfolio
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  flask-app:
    build: .
    container_name: faith-portfolio-app
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql+pymysql://root:secret@mysql:3306/portfolio

volumes:
  mysql_data: